on:
  workflow_dispatch: # これが入っていれば、GASから WORKFLOW_ID 指定で叩けます
  # schedule: ... (GitHub側のタイマーは消してOKです)

jobs:
  test-bq:


  test-bq:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install selenium webdriver-manager gspread google-cloud-bigquery
      
      - name: Run BQ Update (Episode Likes)
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          TVER_DATA_SHEET_ID: ${{ secrets.TVER_DATA_SHEET_ID }}
        run: python episode_like_bq.py

      - name: Run BQ Update (Program Favorites)
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          TVER_DATA_SHEET_ID: ${{ secrets.TVER_DATA_SHEET_ID }}
        run: python program_favorite_bq.py
