name: TVerデータ収集（お気に入り＆いいね）実行

on:
  workflow_dispatch: # 手動実行用
  repository_dispatch:
    types: [gas_trigger] # GASからのキック用
  schedule:
    - cron: '0 * * * *' # 予備の1時間おき実行

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: |
          pip install google-cloud-bigquery selenium requests pandas gspread

      - name: 番組お気に入り数を取得
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: python program_favorite.py

      - name: エピソードいいね数を取得
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: python episode_like.py
