name: 【自動/手動】番組お気に入り収集

on:
  workflow_dispatch: # 手動実行用
  schedule:
    # 日本時間の毎時00分＝UTCの毎時15分
    - cron: "15 * * * *"

jobs:
  run-favorite-only:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install gspread oauth2client selenium==4.18.1

      - name: Run favorite script
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          TVER_DATA_SHEET_ID: ${{ secrets.TVER_DATA_SHEET_ID }}
        run: python program_favorite.py
